//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string speciality { get; set; }
        public string category { get; set; }
        public Nullable<int> amount { get; set; }
    }
}
