//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lb9
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailyPerformance
    {
        public int sleep_amount { get; set; }
        public Nullable<int> step_amount { get; set; }
        public Nullable<int> level_stress { get; set; }
        public Nullable<int> body_condition { get; set; }
        public Nullable<int> mood_level { get; set; }
        public Nullable<int> rest_amount { get; set; }
    }
}
