//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lb9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Номер_заказа { get; set; }
        public string Наименование_товара { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<System.DateTime> Дата_поставки { get; set; }
        public string Заказчик { get; set; }
    
        public virtual Покупатель Покупатель { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
