//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInform
    {
        public string nickname { get; set; }
        public string inform { get; set; }
        public int id { get; set; }
    
        public virtual UserAuth UserAuth { get; set; }
    }
}
